# PRODUCTION STAGE
FROM nginx:stable-alpine3.19-slim

# WORKING WITH NGINX CONFIGURATION
# CHANGE WORKDIR TO NGINX CONFIGURATION LOCATION
WORKDIR /etc/nginx/conf.d
# REPLACE DEFAULT.CONF WITH CUSTOM ONE (FIX REACT ROUTER ERROR 404)
COPY default.conf .

# WORKING WITH ASSETS
# CHANGE WORKDIR TO NGINX ASSETS LOCATION
WORKDIR /usr/share/nginx/html
# REMOVE DEFAULT NGINX STATIC ASSETS
RUN rm -rf ./*
# COPY BUILD FILE TO CONTAINER
COPY ./dist/ .

EXPOSE 80